# Generated by Django 6.0.4 on 2026-07-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootballClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=100)),
                ("sovrinlar", models.PositiveIntegerField(default=0)),
                ("murabbiy", models.CharField(max_length=200)),
                ("stadion", models.CharField(max_length=200)),
                ("tashkl_topgan_yili", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
